### PR TITLE
Korean translation of 1.3.0v file

### PR DESCRIPTION
**Pull request by GlHhwa**
[Korean translation of 1.3.0v.zip](https://github.com/Floogen/DynamicReflections/files/9130181/Korean.translation.of.1.3.0v.zip)

I translated the updated 1.3.0v sky and shooting star in Korean!

### CODE REVIEW

**Review by Floogen — CHANGES_REQUESTED** [review]
Hello there!

This appears to be the [v1.2.1 version of your Korean translation](https://github.com/Floogen/DynamicReflections/blob/development/DynamicReflections/i18n/ko.json). Did you mean to upload the v1.3.0 version?

**Comment by GlHhwa** [comment]
Yes, hello!

I tried to upload the Korean translation ko.json file for 1.3.0v right away, but for some reason, it said it was not a supported format, so I compressed it into a zip file and uploaded it!

If you click the link attached below, the zip file that I compressed will be downloaded.

(https://github.com/Floogen/DynamicReflections/files/9130181/Korean.translation.of.1.3.0v.zip)

I don't know the function of GitHub yet, so I think I'm bothering you. I'm sorry. I'm not good at it, but I really appreciate your kind response.

**Comment by Floogen** [comment]
Ah I see now! I initially missed your attached ZIP file, but I have since pushed it to this PR.

It is no bother at all! The usual and preferred way is to "push" your changes of the translation file to your forked repository, before opening up a pull a request based on that push.

Thank you for the updated translation! I'll include it in the next update.

**Comment by GlHhwa** [comment]
If there's another day I can update the translation, I'll try to do it the way you told me! Thank you for letting me know!

I'll be looking forward to the next update! Thanks to your mode, my Stardew Valley is happy. Especially, this night sky update is romantic and beautiful.

Take care of your health and have a nice day!

**Pull request merged**
